@host = http://localhost:5000

### addVilles
POST {{host}}/addVilles
Content-Type: application/json

< ./fixtures/villes.json


### addVille
POST {{host}}/addVille/2
Content-Type: application/json



### get villes
GET {{host}}/villes

### get villes beginning with letter
GET {{host}}/villes?letter=a


### simple test POST
POST {{host}}/test/5
Content-Type: application/json

{"name":"GGGG"}